#include <stdio.h>
#define MAX 1024

int main(void) {
    int i;
    double d;
    char buf[MAX];

    // Enter a digit.
    scanf("%d", &i);

    // Enter a double.
    //
    // http://forum.codecall.net/topic/37537-how-to-use-scanf-in-c/
    // When reading input with scanf, the input is read after the return key is pressed,
    // but the newline generated by it will not be consumed by scanf. This means the next
    // time you read a char from standard input, the newline will be plugged in instead,
    // thus the skipping.
    //
    // You can avoid this by using fgets, to read the input as a string then extract what
    // you wish with sscanf. Another way would be to catch the newline completely, with
    // scanf("%c%*c",&achar), %*c will read the newline after the buffer, and rightfully discard it.
    scanf("%lf%*c", &d);

    // Enter a string.
    // Accept a multiple word string.
    scanf("%[^\n]s", buf);
    printf("%s\n", buf);

    printf("%d\n", i);
    // Format double with a single precision.
    printf("%.1lf\n", d);
    printf("%s\n", buf);

    return 0;
}

